name:                backend
version:             0.1.0.0
github:              "janschultecom/react-yesod-auth"
license:             ApacheV2
author:              "Jan Schulte"
maintainer:          "example@example.com"
copyright:           "2018 Jan Schulte"

extra-source-files:

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/janschultecom/react-yesod-auth#readme>

dependencies:
- base >= 4.7 && < 5
- text
- servant
- servant-server
- transformers
- aeson
- wai
- warp
- dotenv
- directory
- http-client

library:
  source-dirs: src

executables:
  backend-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend

tests:
  backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backend
